---
name: Check URLs 🔗

on:
  # 'push' events are triggered when commits
  # are pushed to one of these branches
  push:
    branches:
      - main
    tags:
      - "v*"
  # 'pull_request' events are triggered when PRs are
  # created against one of these target branches.
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
      - main
  # 'workflow_dispatch' gives you the ability
  # to run this workflow on demand, anytime
  workflow_dispatch:

concurrency:
  group: links-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  links:
    name: Validate Links 🕸️
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip links]')
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v4

      - name: Check URLs in docs 📑
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          jobSummary: true
          format: markdown
          output: links-results.md
          args: >-
            --exclude-private
            --exclude "https://github.com.*.git|lycheeverse.*"
            --verbose
            --no-progress
            **/*.md
            **/*.html
            **/*.Rmd
            **/*.yaml
            **/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
