---
name: Deploy pkgdown site 📜

on:
  push:
    branches:
      - main

concurrency:
  group: docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    if: >
      !contains(github.event.commits[0].message, '[skip docs]')
        && github.event.pull_request.draft == false
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v4

      - name: Setup R 📊
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R package dependencies 📦
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Deploy package ☁️
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
