---
name: Check Spelling 🆎

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  spelling:
    name: Run Spellcheck 👟
    uses: insightsengineering/r-spellcheck-action@v3
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      exclude: data/*,**/*.Rd,**/*.md,*.md
