---
name: Check Spelling 🆎

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spelling:
    name: Run Spellcheck 👟
    runs-on: ubuntu-latest
    # exclude: data/*,**/*.Rd,**/*.md,*.md
    if: >
      !contains(github.event.commits[0].message, '[skip spellcheck]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::spelling

      - name: Run Spelling Check test
        uses: insightsengineering/r-spellcheck-action@v2
