name: Check Test Coverage 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Necessary to avoid object usage linter errors.
          extra-packages: local::., any::covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
