name: Check Test Coverage 🧪

on:
  # 'push' events are triggered when commits
  # are pushed to one of these branches
  push:
    branches:
      - main
    tags:
      - "v*"
  # 'pull_request' events are triggered when PRs are
  # created against one of these target branches.
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
      - main
  # 'workflow_dispatch' gives you the ability
  # to run this workflow on demand, anytime
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage 📔
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip coverage]')
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v4

      - name: Setup R 📊
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Necessary to avoid object usage linter errors.
          extra-packages: local::., any::covr

      - name: Run Test coverage 👟
        run: covr::codecov()
        shell: Rscript {0}
