name: Check Test Coverage 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    name: Coverage 📔
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip coverage]')
        && github.event.pull_request.draft == false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v4

      - name: Setup R 📊
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Necessary to avoid object usage linter errors.
          extra-packages: local::., any::covr

      - name: Run Test coverage 👟
        run: covr::codecov()
        shell: Rscript {0}
